name = "kasane-website-new"
main = "src/index.tsx"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# 静的ファイル配信を有効化
[site]
bucket = "public"

[vars]
ENVIRONMENT = "production"
STRAPI_URL = "https://your-strapi-cloud.strapiapp.com"
STRAPI_API_TOKEN = ""